# Generated by Django 6.0.3 on 2026-08-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0008_testattempt_questionattempt_uploadeddocument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='expertise_field',
        ),
    ]
